import type { Region } from "./index";

export const regions: Region[] = [
  { code: "bg01", name: "Blagoevgrad", plate: 1 },
  { code: "bg02", name: "Burgas", plate: 2 },
  { code: "bg03", name: "Varna", plate: 3 },
  { code: "bg04", name: "Veliko Tarnovo", plate: 4 },
  { code: "bg05", name: "Vidin", plate: 5 },
  { code: "bg06", name: "Vratsa", plate: 6 },
  { code: "bg07", name: "Gabrovo", plate: 7 },
  { code: "bg08", name: "Dobrich", plate: 8 },
  { code: "bg09", name: "Kardzhali", plate: 9 },
  { code: "bg10", name: "Kyustendil", plate: 10 },
  { code: "bg11", name: "Lovech", plate: 11 },
  { code: "bg12", name: "Montana", plate: 12 },
  { code: "bg13", name: "Pazardzhik", plate: 13 },
  { code: "bg14", name: "Pernik", plate: 14 },
  { code: "bg15", name: "Pleven", plate: 15 },
  { code: "bg16", name: "Plovdiv", plate: 16 },
  { code: "bg17", name: "Razgrad", plate: 17 },
  { code: "bg18", name: "Ruse", plate: 18 },
  { code: "bg19", name: "Silistra", plate: 19 },
  { code: "bg20", name: "Sliven", plate: 20 },
  { code: "bg21", name: "Smolyan", plate: 21 },
  { code: "bg22", name: "Grad Sofiya", plate: 22 },
  { code: "bg23", name: "Sofia", plate: 23 },
  { code: "bg24", name: "Stara Zagora", plate: 24 },
  { code: "bg25", name: "Targovishte", plate: 25 },
  { code: "bg26", name: "Haskovo", plate: 26 },
  { code: "bg27", name: "Shumen", plate: 27 },
  { code: "bg28", name: "Yambol", plate: 28 },
];