import type { Region } from "./index";

export const regions: Region[] = [
  { code: "brac", name: "Acre", plate: 1 },
  { code: "bral", name: "Alagoas", plate: 2 },
  { code: "bram", name: "Amazonas", plate: 3 },
  { code: "brap", name: "Amapá", plate: 4 },
  { code: "brba", name: "Bahia", plate: 5 },
  { code: "brce", name: "Ceará", plate: 6 },
  { code: "brdf", name: "Distrito Federal", plate: 7 },
  { code: "bres", name: "Espírito Santo", plate: 8 },
  { code: "brgo", name: "Goiás", plate: 9 },
  { code: "brma", name: "Maranhão", plate: 10 },
  { code: "brmg", name: "Minas Gerais", plate: 11 },
  { code: "brms", name: "Mato Grosso do Sul", plate: 12 },
  { code: "brmt", name: "Mato Grosso", plate: 13 },
  { code: "brpa", name: "Pará", plate: 14 },
  { code: "brpb", name: "Paraíba", plate: 15 },
  { code: "brpe", name: "Pernambuco", plate: 16 },
  { code: "brpi", name: "Piauí", plate: 17 },
  { code: "brpr", name: "Paraná", plate: 18 },
  { code: "brrj", name: "Rio de Janeiro", plate: 19 },
  { code: "brrn", name: "Rio Grande do Norte", plate: 20 },
  { code: "brro", name: "Rondônia", plate: 21 },
  { code: "brrr", name: "Roraima", plate: 22 },
  { code: "brrs", name: "Rio Grande do Sul", plate: 23 },
  { code: "brsc", name: "Santa Catarina", plate: 24 },
  { code: "brse", name: "Sergipe", plate: 25 },
  { code: "brsp", name: "São Paulo", plate: 26 },
  { code: "brto", name: "Tocantins", plate: 27 },
];