import type { Region } from "./index";

export const regions: Region[] = [
  { code: "cnah", name: "Anhui Province", plate: 1 },
  { code: "cnbj", name: "Beijing Municipality", plate: 2 },
  { code: "cncq", name: "Chongqing Municipality", plate: 3 },
  { code: "cnfj", name: "Fujian Province", plate: 4 },
  { code: "cngd", name: "Guangdong Province", plate: 5 },
  { code: "cngs", name: "Gansu province", plate: 6 },
  { code: "cngx", name: "Guangxi Zhuang Autonomous Region", plate: 7 },
  { code: "cngz", name: "Guizhou Province", plate: 8 },
  { code: "cnha", name: "Henan Province", plate: 9 },
  { code: "cnhb", name: "Hubei Province", plate: 10 },
  { code: "cnhe", name: "Hebei Province", plate: 11 },
  { code: "cnhi", name: "Hainan Province", plate: 12 },
  { code: "cnhk", name: "Hong Kong Special Administrative Region", plate: 13 },
  { code: "cnhl", name: "Heilongjiang Province", plate: 14 },
  { code: "cnhn", name: "Hunan Province", plate: 15 },
  { code: "cnjl", name: "Jilin Province", plate: 16 },
  { code: "cnjs", name: "Jiangsu Province", plate: 17 },
  { code: "cnjx", name: "Jiangxi Province", plate: 18 },
  { code: "cnln", name: "Liaoning Province", plate: 19 },
  { code: "cnmo", name: "Macao Special Administrative Region", plate: 20 },
  { code: "cnnm", name: "Inner Mongolia Autonomous Region", plate: 21 },
  { code: "cnnx", name: "Ningxia Hui Autonomous Region", plate: 22 },
  { code: "cnqh", name: "Qinghai Province", plate: 23 },
  { code: "cnsc", name: "Sichuan Province", plate: 24 },
  { code: "cnsd", name: "Shandong Province", plate: 25 },
  { code: "cnsh", name: "Shanghai Municipality", plate: 26 },
  { code: "cnsn", name: "Shaanxi Province", plate: 27 },
  { code: "cnsx", name: "Shanxi Province", plate: 28 },
  { code: "cntj", name: "Tianjin Municipality", plate: 29 },
  { code: "cntw", name: "Taiwan Province", plate: 30 },
  { code: "cnxj", name: "Xinjiang Uygur Autonomous Region", plate: 31 },
  { code: "cnxz", name: "Tibet Autonomous Region", plate: 32 },
  { code: "cnyn", name: "Yunnan Province", plate: 33 },
  { code: "cnzj", name: "Zhejiang Province", plate: 34 },
];