import type { Region } from "./index";

export const regions: Region[] = [
  { code: "esa", name: "Alicante", plate: 1 },
  { code: "esab", name: "Albacete", plate: 2 },
  { code: "esal", name: "Almería", plate: 3 },
  { code: "esav", name: "Ávila", plate: 4 },
  { code: "esb", name: "Barcelona", plate: 5 },
  { code: "esba", name: "Badajoz", plate: 6 },
  { code: "esbi", name: "Bizkaia", plate: 7 },
  { code: "esbu", name: "Burgos", plate: 8 },
  { code: "esc", name: "La Coruña", plate: 9 },
  { code: "esca", name: "Cádiz", plate: 10 },
  { code: "escc", name: "Cáceres", plate: 11 },
  { code: "esce", name: "Ceuta", plate: 12 },
  { code: "esco", name: "Córdoba", plate: 13 },
  { code: "escr", name: "Ciudad Real", plate: 14 },
  { code: "escs", name: "Castellón", plate: 15 },
  { code: "escu", name: "Cuenca", plate: 16 },
  { code: "esgc", name: "Las Palmas", plate: 17 },
  { code: "esgi", name: "Gerona", plate: 18 },
  { code: "esgr", name: "Granada", plate: 19 },
  { code: "esgu", name: "Guadalajara", plate: 20 },
  { code: "esh", name: "Huelva", plate: 21 },
  { code: "eshu", name: "Huesca", plate: 22 },
  { code: "esj", name: "Jaén", plate: 23 },
  { code: "esl", name: "Lérida", plate: 24 },
  { code: "esle", name: "León", plate: 25 },
  { code: "eslo", name: "La Rioja", plate: 26 },
  { code: "eslu", name: "Lugo", plate: 27 },
  { code: "esm", name: "Madrid", plate: 28 },
  { code: "esma", name: "Málaga", plate: 29 },
  { code: "esml", name: "Melilla", plate: 30 },
  { code: "esmu", name: "Murcia", plate: 31 },
  { code: "esna", name: "Navarra", plate: 32 },
  { code: "eso", name: "Asturias", plate: 33 },
  { code: "esor", name: "Orense", plate: 34 },
  { code: "esp", name: "Palencia", plate: 35 },
  { code: "espm", name: "Baleares", plate: 36 },
  { code: "espo", name: "Pontevedra", plate: 37 },
  { code: "ess", name: "Cantabria", plate: 38 },
  { code: "essa", name: "Salamanca", plate: 39 },
  { code: "esse", name: "Sevilla", plate: 40 },
  { code: "essg", name: "Segovia", plate: 41 },
  { code: "esso", name: "Soria", plate: 42 },
  { code: "esss", name: "Gipuzkoa", plate: 43 },
  { code: "est", name: "Tarragona", plate: 44 },
  { code: "este", name: "Teruel", plate: 45 },
  { code: "estf", name: "Santa Cruz de Tenerife", plate: 46 },
  { code: "esto", name: "Toledo", plate: 47 },
  { code: "esv", name: "Valencia", plate: 48 },
  { code: "esva", name: "Valladolid", plate: 49 },
  { code: "esvi", name: "Álava", plate: 50 },
  { code: "esz", name: "Zaragoza", plate: 51 },
  { code: "esza", name: "Zamora", plate: 52 },
];