import type { Region } from "./index";

export const regions: Region[] = [
  { code: "gbabd", name: "Aberdeenshire", plate: 1 },
  { code: "gbabe", name: "Aberdeen", plate: 2 },
  { code: "gbagb", name: "Argyll and Bute", plate: 3 },
  { code: "gbagy", name: "Anglesey", plate: 4 },
  { code: "gbans", name: "Angus", plate: 5 },
  { code: "gbant", name: "Antrim", plate: 6 },
  { code: "gbard", name: "Ards", plate: 7 },
  { code: "gbarm", name: "Armagh", plate: 8 },
  { code: "gbbas", name: "Bath and North East Somerset", plate: 9 },
  { code: "gbbbd", name: "Blackburn with Darwen", plate: 10 },
  { code: "gbbdf", name: "Bedford", plate: 11 },
  { code: "gbbdg", name: "Barking and Dagenham", plate: 12 },
  { code: "gbben", name: "Brent", plate: 13 },
  { code: "gbbex", name: "Bexley", plate: 14 },
  { code: "gbbfs", name: "Belfast", plate: 15 },
  { code: "gbbge", name: "Bridgend", plate: 16 },
  { code: "gbbgw", name: "Blaenau Gwent", plate: 17 },
  { code: "gbbir", name: "Birmingham", plate: 18 },
  { code: "gbbkm", name: "Buckinghamshire", plate: 19 },
  { code: "gbbla", name: "Ballymena", plate: 20 },
  { code: "gbbly", name: "Ballymoney", plate: 21 },
  { code: "gbbmh", name: "Bournemouth", plate: 22 },
  { code: "gbbnb", name: "Banbridge", plate: 23 },
  { code: "gbbne", name: "Barnet", plate: 24 },
  { code: "gbbnh", name: "Brighton and Hove", plate: 25 },
  { code: "gbbns", name: "Barnsley", plate: 26 },
  { code: "gbbol", name: "Bolton", plate: 27 },
  { code: "gbbpl", name: "Blackpool", plate: 28 },
  { code: "gbbrc", name: "Bracknell Forest", plate: 29 },
  { code: "gbbrd", name: "Bradford", plate: 30 },
  { code: "gbbry", name: "Bromley", plate: 31 },
  { code: "gbbst", name: "Bristol", plate: 32 },
  { code: "gbbur", name: "Bury", plate: 33 },
  { code: "gbcam", name: "Cambridgeshire", plate: 34 },
  { code: "gbcay", name: "Caerphilly", plate: 35 },
  { code: "gbcbf", name: "Central Bedfordshire", plate: 36 },
  { code: "gbcgn", name: "Ceredigion", plate: 37 },
  { code: "gbcgv", name: "Craigavon", plate: 38 },
  { code: "gbche", name: "Cheshire East", plate: 39 },
  { code: "gbchw", name: "Cheshire West and Chester", plate: 40 },
  { code: "gbckf", name: "Carrickfergus", plate: 41 },
  { code: "gbckt", name: "Mid Ulster", plate: 42 },
  { code: "gbcld", name: "Calderdale", plate: 43 },
  { code: "gbclk", name: "Clackmannanshire", plate: 44 },
  { code: "gbclr", name: "Coleraine", plate: 45 },
  { code: "gbcma", name: "Cumbria", plate: 46 },
  { code: "gbcmd", name: "Camden", plate: 47 },
  { code: "gbcmn", name: "Carmarthenshire", plate: 48 },
  { code: "gbcon", name: "Cornwall", plate: 49 },
  { code: "gbcov", name: "Coventry", plate: 50 },
  { code: "gbcrf", name: "Cardiff", plate: 51 },
  { code: "gbcry", name: "Croydon", plate: 52 },
  { code: "gbcsr", name: "Castlereagh", plate: 53 },
  { code: "gbcwy", name: "Conwy", plate: 54 },
  { code: "gbdal", name: "Darlington", plate: 55 },
  { code: "gbdby", name: "Derbyshire", plate: 56 },
  { code: "gbden", name: "Denbighshire", plate: 57 },
  { code: "gbder", name: "Derby", plate: 58 },
  { code: "gbdev", name: "Devon", plate: 59 },
  { code: "gbdgn", name: "Dungannon", plate: 60 },
  { code: "gbdgy", name: "Dumfries and Galloway", plate: 61 },
  { code: "gbdnc", name: "Doncaster", plate: 62 },
  { code: "gbdnd", name: "Dundee", plate: 63 },
  { code: "gbdor", name: "Dorset", plate: 64 },
  { code: "gbdow", name: "Down", plate: 65 },
  { code: "gbdry", name: "Derry", plate: 66 },
  { code: "gbdud", name: "Dudley", plate: 67 },
  { code: "gbdur", name: "Durham", plate: 68 },
  { code: "gbeal", name: "Ealing", plate: 69 },
  { code: "gbeay", name: "East Ayrshire", plate: 70 },
  { code: "gbedh", name: "Edinburgh", plate: 71 },
  { code: "gbedu", name: "East Dunbartonshire", plate: 72 },
  { code: "gbeln", name: "East Lothian", plate: 73 },
  { code: "gbels", name: "Eilean Siar", plate: 74 },
  { code: "gbenf", name: "Enfield", plate: 75 },
  { code: "gberw", name: "East Renfrewshire", plate: 76 },
  { code: "gbery", name: "East Riding of Yorkshire", plate: 77 },
  { code: "gbess", name: "Essex", plate: 78 },
  { code: "gbesx", name: "East Sussex", plate: 79 },
  { code: "gbfal", name: "Falkirk", plate: 80 },
  { code: "gbfer", name: "Fermanagh", plate: 81 },
  { code: "gbfif", name: "Fife", plate: 82 },
  { code: "gbfln", name: "Flintshire", plate: 83 },
  { code: "gbgat", name: "Gateshead", plate: 84 },
  { code: "gbglg", name: "Glasgow", plate: 85 },
  { code: "gbgls", name: "Gloucestershire", plate: 86 },
  { code: "gbgre", name: "Greenwich", plate: 87 },
  { code: "gbgwn", name: "Gwynedd", plate: 88 },
  { code: "gbhal", name: "Halton", plate: 89 },
  { code: "gbham", name: "Hampshire", plate: 90 },
  { code: "gbhav", name: "Havering", plate: 91 },
  { code: "gbhck", name: "Hackney", plate: 92 },
  { code: "gbhef", name: "Herefordshire", plate: 93 },
  { code: "gbhil", name: "Hillingdon", plate: 94 },
  { code: "gbhld", name: "Highland", plate: 95 },
  { code: "gbhmf", name: "Hammersmith and Fulham", plate: 96 },
  { code: "gbhns", name: "Hounslow", plate: 97 },
  { code: "gbhpl", name: "Hartlepool", plate: 98 },
  { code: "gbhrt", name: "Hertfordshire", plate: 99 },
  { code: "gbhrw", name: "Harrow", plate: 100 },
  { code: "gbhry", name: "Haringey", plate: 101 },
  { code: "gbios", name: "Isles of Scilly", plate: 102 },
  { code: "gbiow", name: "Isle of Wight", plate: 103 },
  { code: "gbisl", name: "Islington", plate: 104 },
  { code: "gbivc", name: "Inverclyde", plate: 105 },
  { code: "gbkec", name: "Kensington and Chelsea", plate: 106 },
  { code: "gbken", name: "Kent", plate: 107 },
  { code: "gbkhl", name: "Kingston upon Hull", plate: 108 },
  { code: "gbkir", name: "Kirklees", plate: 109 },
  { code: "gbktt", name: "Kingston upon Thames", plate: 110 },
  { code: "gbkwl", name: "Knowsley", plate: 111 },
  { code: "gblan", name: "Lancashire", plate: 112 },
  { code: "gblbh", name: "Lambeth", plate: 113 },
  { code: "gblce", name: "Leicester", plate: 114 },
  { code: "gblds", name: "Leeds", plate: 115 },
  { code: "gblec", name: "Leicestershire", plate: 116 },
  { code: "gblew", name: "Lewisham", plate: 117 },
  { code: "gblin", name: "Lincolnshire", plate: 118 },
  { code: "gbliv", name: "Liverpool", plate: 119 },
  { code: "gblmv", name: "Limavady", plate: 120 },
  { code: "gblnd", name: "City", plate: 121 },
  { code: "gblrn", name: "Larne", plate: 122 },
  { code: "gblsb", name: "Lisburn", plate: 123 },
  { code: "gblut", name: "Luton", plate: 124 },
  { code: "gbman", name: "Manchester", plate: 125 },
  { code: "gbmdb", name: "Middlesbrough", plate: 126 },
  { code: "gbmdw", name: "Medway", plate: 127 },
  { code: "gbmft", name: "Magherafelt", plate: 128 },
  { code: "gbmik", name: "Milton Keynes", plate: 129 },
  { code: "gbmln", name: "Midlothian", plate: 130 },
  { code: "gbmon", name: "Monmouthshire", plate: 131 },
  { code: "gbmrt", name: "Merton", plate: 132 },
  { code: "gbmry", name: "Moray", plate: 133 },
  { code: "gbmty", name: "Merthyr Tydfil", plate: 134 },
  { code: "gbmyl", name: "Moyle", plate: 135 },
  { code: "gbnay", name: "North Ayshire", plate: 136 },
  { code: "gbnbl", name: "Northumberland", plate: 137 },
  { code: "gbndn", name: "North Down", plate: 138 },
  { code: "gbnel", name: "North East Lincolnshire", plate: 139 },
  { code: "gbnet", name: "Newcastle upon Tyne", plate: 140 },
  { code: "gbnfk", name: "Norfolk", plate: 141 },
  { code: "gbngm", name: "Nottingham", plate: 142 },
  { code: "gbnlk", name: "North Lanarkshire", plate: 143 },
  { code: "gbnln", name: "North Lincolnshire", plate: 144 },
  { code: "gbnsm", name: "North Somerset", plate: 145 },
  { code: "gbnta", name: "Newtownabbey", plate: 146 },
  { code: "gbnth", name: "Northamptonshire", plate: 147 },
  { code: "gbntl", name: "Neath Port Talbot", plate: 148 },
  { code: "gbntt", name: "Nottinghamshire", plate: 149 },
  { code: "gbnty", name: "North Tyneside", plate: 150 },
  { code: "gbnwm", name: "Newham", plate: 151 },
  { code: "gbnwp", name: "Newport", plate: 152 },
  { code: "gbnyk", name: "North Yorkshire", plate: 153 },
  { code: "gbnym", name: "Newry and Mourne", plate: 154 },
  { code: "gbold", name: "Oldham", plate: 155 },
  { code: "gbomh", name: "Omagh", plate: 156 },
  { code: "gbork", name: "Orkney", plate: 157 },
  { code: "gboxf", name: "Oxfordshire", plate: 158 },
  { code: "gbpem", name: "Pembrokeshire", plate: 159 },
  { code: "gbpkn", name: "Perthshire and Kinross", plate: 160 },
  { code: "gbply", name: "Plymouth", plate: 161 },
  { code: "gbpol", name: "Poole", plate: 162 },
  { code: "gbpor", name: "Portsmouth", plate: 163 },
  { code: "gbpow", name: "Powys", plate: 164 },
  { code: "gbpte", name: "Peterborough", plate: 165 },
  { code: "gbrcc", name: "Redcar and Cleveland", plate: 166 },
  { code: "gbrch", name: "Rochdale", plate: 167 },
  { code: "gbrct", name: "Rhondda, Cynon, Taff", plate: 168 },
  { code: "gbrdb", name: "Redbridge", plate: 169 },
  { code: "gbrdg", name: "Reading", plate: 170 },
  { code: "gbrfw", name: "Renfrewshire", plate: 171 },
  { code: "gbric", name: "Richmond upon Thames", plate: 172 },
  { code: "gbrot", name: "Rotherham", plate: 173 },
  { code: "gbrut", name: "Rutland", plate: 174 },
  { code: "gbsaw", name: "Sandwell", plate: 175 },
  { code: "gbsay", name: "South Ayrshire", plate: 176 },
  { code: "gbscb", name: "Scottish Borders", plate: 177 },
  { code: "gbsfk", name: "Suffolk", plate: 178 },
  { code: "gbsft", name: "Sefton", plate: 179 },
  { code: "gbsgc", name: "South Gloucestershire", plate: 180 },
  { code: "gbshf", name: "Sheffield", plate: 181 },
  { code: "gbshn", name: "Merseyside", plate: 182 },
  { code: "gbshr", name: "Shropshire", plate: 183 },
  { code: "gbskp", name: "Stockport", plate: 184 },
  { code: "gbslf", name: "Salford", plate: 185 },
  { code: "gbslg", name: "Slough", plate: 186 },
  { code: "gbslk", name: "South Lanarkshire", plate: 187 },
  { code: "gbsnd", name: "Sunderland", plate: 188 },
  { code: "gbsol", name: "Solihull", plate: 189 },
  { code: "gbsom", name: "Somerset", plate: 190 },
  { code: "gbsos", name: "Southend-on-Sea", plate: 191 },
  { code: "gbsry", name: "Surrey", plate: 192 },
  { code: "gbstb", name: "Strabane", plate: 193 },
  { code: "gbste", name: "Stoke-on-Trent", plate: 194 },
  { code: "gbstg", name: "Stirling", plate: 195 },
  { code: "gbsth", name: "Southampton", plate: 196 },
  { code: "gbstn", name: "Sutton", plate: 197 },
  { code: "gbsts", name: "Staffordshire", plate: 198 },
  { code: "gbstt", name: "Stockton-on-Tees", plate: 199 },
  { code: "gbsty", name: "South Tyneside", plate: 200 },
  { code: "gbswa", name: "Swansea", plate: 201 },
  { code: "gbswd", name: "Swindon", plate: 202 },
  { code: "gbswk", name: "Southwark", plate: 203 },
  { code: "gbtam", name: "Tameside", plate: 204 },
  { code: "gbtfw", name: "Telford and Wrekin", plate: 205 },
  { code: "gbthr", name: "Thurrock", plate: 206 },
  { code: "gbtob", name: "Torbay", plate: 207 },
  { code: "gbtof", name: "Torfaen", plate: 208 },
  { code: "gbtrf", name: "Trafford", plate: 209 },
  { code: "gbtwh", name: "Tower Hamlets", plate: 210 },
  { code: "gbvgl", name: "Vale of Glamorgan", plate: 211 },
  { code: "gbwar", name: "Warwickshire", plate: 212 },
  { code: "gbwbk", name: "West Berkshire", plate: 213 },
  { code: "gbwdu", name: "West Dunbartonshire", plate: 214 },
  { code: "gbwft", name: "Waltham Forest", plate: 215 },
  { code: "gbwgn", name: "Wigan", plate: 216 },
  { code: "gbwil", name: "Wiltshire", plate: 217 },
  { code: "gbwkf", name: "Wakefield", plate: 218 },
  { code: "gbwll", name: "Walsall", plate: 219 },
  { code: "gbwln", name: "West Lothian", plate: 220 },
  { code: "gbwlv", name: "Wolverhampton", plate: 221 },
  { code: "gbwnd", name: "Wandsworth", plate: 222 },
  { code: "gbwnm", name: "Royal Borough of Windsor and Maidenhead", plate: 223 },
  { code: "gbwok", name: "Wokingham", plate: 224 },
  { code: "gbwor", name: "Worcestershire", plate: 225 },
  { code: "gbwrl", name: "Halton", plate: 226 },
  { code: "gbwrt", name: "Warrington", plate: 227 },
  { code: "gbwrx", name: "Wrexham", plate: 228 },
  { code: "gbwsm", name: "Westminster", plate: 229 },
  { code: "gbwsx", name: "West Sussex", plate: 230 },
  { code: "gbyor", name: "York", plate: 231 },
  { code: "gbzet", name: "Shetland Islands", plate: 232 },
];