import type { Region } from "./index";

export const regions: Region[] = [
  { code: "itag", name: "Agrigento", plate: 1 },
  { code: "ital", name: "Alessandria", plate: 2 },
  { code: "itan", name: "Ancona", plate: 3 },
  { code: "itao", name: "Aoste", plate: 4 },
  { code: "itap", name: "Ascoli Piceno", plate: 5 },
  { code: "itaq", name: "L'Aquila", plate: 6 },
  { code: "itar", name: "Arezzo", plate: 7 },
  { code: "itat", name: "Asti", plate: 8 },
  { code: "itav", name: "Avellino", plate: 9 },
  { code: "itba", name: "Bari", plate: 10 },
  { code: "itbg", name: "Bergamo", plate: 11 },
  { code: "itbi", name: "Biella", plate: 12 },
  { code: "itbl", name: "Belluno", plate: 13 },
  { code: "itbn", name: "Benevento", plate: 14 },
  { code: "itbo", name: "Bologna", plate: 15 },
  { code: "itbr", name: "Brindisi", plate: 16 },
  { code: "itbs", name: "Brescia", plate: 17 },
  { code: "itbt", name: "Barletta-Andria Trani", plate: 18 },
  { code: "itbz", name: "Bozen", plate: 19 },
  { code: "itca", name: "Cagliari", plate: 20 },
  { code: "itcb", name: "Campobasso", plate: 21 },
  { code: "itce", name: "Caserta", plate: 22 },
  { code: "itch", name: "Chieti", plate: 23 },
  { code: "itcl", name: "Caltanissetta", plate: 24 },
  { code: "itcn", name: "Cuneo", plate: 25 },
  { code: "itco", name: "Como", plate: 26 },
  { code: "itcr", name: "Cremona", plate: 27 },
  { code: "itcs", name: "Cosenza", plate: 28 },
  { code: "itct", name: "Catania", plate: 29 },
  { code: "itcz", name: "Catanzaro", plate: 30 },
  { code: "iten", name: "Enna", plate: 31 },
  { code: "itfc", name: "Forlì-Cesena", plate: 32 },
  { code: "itfe", name: "Ferrara", plate: 33 },
  { code: "itfg", name: "Foggia", plate: 34 },
  { code: "itfi", name: "Firenze", plate: 35 },
  { code: "itfm", name: "Fermo", plate: 36 },
  { code: "itfr", name: "Frosinone", plate: 37 },
  { code: "itge", name: "Genova", plate: 38 },
  { code: "itgo", name: "Gorizia", plate: 39 },
  { code: "itgr", name: "Grosseto", plate: 40 },
  { code: "itim", name: "Imperia", plate: 41 },
  { code: "itis", name: "Isernia", plate: 42 },
  { code: "itkr", name: "Crotene", plate: 43 },
  { code: "itlc", name: "Lecco", plate: 44 },
  { code: "itle", name: "Lecce", plate: 45 },
  { code: "itli", name: "Livorno", plate: 46 },
  { code: "itlo", name: "Lodi", plate: 47 },
  { code: "itlt", name: "Latina", plate: 48 },
  { code: "itlu", name: "Lucca", plate: 49 },
  { code: "itmb", name: "Monza e Brianza", plate: 50 },
  { code: "itmc", name: "Macerata", plate: 51 },
  { code: "itme", name: "Messina", plate: 52 },
  { code: "itmi", name: "Milano", plate: 53 },
  { code: "itmn", name: "Mantova", plate: 54 },
  { code: "itmo", name: "Modena", plate: 55 },
  { code: "itms", name: "Massa-Carrara", plate: 56 },
  { code: "itmt", name: "Matera", plate: 57 },
  { code: "itna", name: "Napoli", plate: 58 },
  { code: "itno", name: "Novara", plate: 59 },
  { code: "itnu", name: "Nuoro", plate: 60 },
  { code: "itor", name: "Oristrano", plate: 61 },
  { code: "itpa", name: "Palermo", plate: 62 },
  { code: "itpc", name: "Piacenza", plate: 63 },
  { code: "itpd", name: "Padova", plate: 64 },
  { code: "itpe", name: "Pescara", plate: 65 },
  { code: "itpg", name: "Perugia", plate: 66 },
  { code: "itpi", name: "Pisa", plate: 67 },
  { code: "itpn", name: "Pordenone", plate: 68 },
  { code: "itpo", name: "Prato", plate: 69 },
  { code: "itpr", name: "Parma", plate: 70 },
  { code: "itpt", name: "Pistoia", plate: 71 },
  { code: "itpu", name: "Pesaro e Urbino", plate: 72 },
  { code: "itpv", name: "Pavia", plate: 73 },
  { code: "itpz", name: "Potenza", plate: 74 },
  { code: "itra", name: "Ravenna", plate: 75 },
  { code: "itrc", name: "Reggio Calabria", plate: 76 },
  { code: "itre", name: "Reggio Emilia", plate: 77 },
  { code: "itrg", name: "Ragusa", plate: 78 },
  { code: "itri", name: "Rieti", plate: 79 },
  { code: "itrm", name: "Roma", plate: 80 },
  { code: "itrn", name: "Rimini", plate: 81 },
  { code: "itro", name: "Rovigo", plate: 82 },
  { code: "itsa", name: "Salerno", plate: 83 },
  { code: "itsi", name: "Siena", plate: 84 },
  { code: "itso", name: "Sondrio", plate: 85 },
  { code: "itsp", name: "La Spezia", plate: 86 },
  { code: "itsr", name: "Siracusa", plate: 87 },
  { code: "itss", name: "Sassari", plate: 88 },
  { code: "itsu", name: "Sud Sardegna", plate: 89 },
  { code: "itsv", name: "Savona", plate: 90 },
  { code: "itta", name: "Taranto", plate: 91 },
  { code: "itte", name: "Teramo", plate: 92 },
  { code: "ittn", name: "Trento", plate: 93 },
  { code: "itto", name: "Turin", plate: 94 },
  { code: "ittp", name: "Trapani", plate: 95 },
  { code: "ittr", name: "Terni", plate: 96 },
  { code: "itts", name: "Trieste", plate: 97 },
  { code: "ittv", name: "Treviso", plate: 98 },
  { code: "itud", name: "Udine", plate: 99 },
  { code: "itva", name: "Varese", plate: 100 },
  { code: "itvb", name: "Verbano-Cusio-Ossola", plate: 101 },
  { code: "itvc", name: "Vercelli", plate: 102 },
  { code: "itve", name: "Venezia", plate: 103 },
  { code: "itvi", name: "Vicenza", plate: 104 },
  { code: "itvr", name: "Verona", plate: 105 },
  { code: "itvt", name: "Viterbo", plate: 106 },
  { code: "itvv", name: "Vibo Valentia", plate: 107 },
];