import type { Region } from "./index";

export const states: Region[] = [
  { code: "ak", name: "Alaska", plate: 1 },
  { code: "al", name: "Alabama", plate: 2 },
  { code: "ar", name: "Arkansas", plate: 3 },
  { code: "az", name: "Arizona", plate: 4 },
  { code: "ca", name: "California", plate: 5 },
  { code: "co", name: "Colorado", plate: 6 },
  { code: "ct", name: "Connecticut", plate: 7 },
  { code: "dc", name: "District of Columbia", plate: 8 },
  { code: "de", name: "Delaware", plate: 9 },
  { code: "fl", name: "Florida", plate: 10 },
  { code: "ga", name: "Georgia", plate: 11 },
  { code: "hi", name: "Hawaii", plate: 12 },
  { code: "ia", name: "Iowa", plate: 13 },
  { code: "id", name: "Idaho", plate: 14 },
  { code: "il", name: "Illinois", plate: 15 },
  { code: "in", name: "Indiana", plate: 16 },
  { code: "ks", name: "Kansas", plate: 17 },
  { code: "ky", name: "Kentucky", plate: 18 },
  { code: "la", name: "Louisiana", plate: 19 },
  { code: "ma", name: "Massachusetts", plate: 20 },
  { code: "md", name: "Maryland", plate: 21 },
  { code: "me", name: "Maine", plate: 22 },
  { code: "mi", name: "Michigan", plate: 23 },
  { code: "mn", name: "Minnesota", plate: 24 },
  { code: "mo", name: "Missouri", plate: 25 },
  { code: "ms", name: "Mississippi", plate: 26 },
  { code: "mt", name: "Montana", plate: 27 },
  { code: "nc", name: "North Carolina", plate: 28 },
  { code: "nd", name: "North Dakota", plate: 29 },
  { code: "ne", name: "Nebraska", plate: 30 },
  { code: "nh", name: "New Hampshire", plate: 31 },
  { code: "nj", name: "New Jersey", plate: 32 },
  { code: "nm", name: "New Mexico", plate: 33 },
  { code: "nv", name: "Nevada", plate: 34 },
  { code: "ny", name: "New York", plate: 35 },
  { code: "oh", name: "Ohio", plate: 36 },
  { code: "ok", name: "Oklahoma", plate: 37 },
  { code: "or", name: "Oregon", plate: 38 },
  { code: "pa", name: "Pennsylvania", plate: 39 },
  { code: "ri", name: "Rhode Island", plate: 40 },
  { code: "sc", name: "South Carolina", plate: 41 },
  { code: "sd", name: "South Dakota", plate: 42 },
  { code: "tn", name: "Tennessee", plate: 43 },
  { code: "tx", name: "Texas", plate: 44 },
  { code: "ut", name: "Utah", plate: 45 },
  { code: "va", name: "Virginia", plate: 46 },
  { code: "vt", name: "Vermont", plate: 47 },
  { code: "wa", name: "Washington", plate: 48 },
  { code: "wi", name: "Wisconsin", plate: 49 },
  { code: "wv", name: "West Virginia", plate: 50 },
  { code: "wy", name: "Wyoming", plate: 51 },
];