import type { Region } from "./index";

export const regions: Region[] = [
  { code: "ae", name: "United Arab Emirates", plate: 1 },
  { code: "af", name: "Afghanistan", plate: 2 },
  { code: "ai", name: "Anguilla", plate: 3 },
  { code: "al", name: "Albania", plate: 4 },
  { code: "am", name: "Armenia", plate: 5 },
  { code: "ao", name: "Angola", plate: 6 },
  { code: "ar", name: "Argentina", plate: 7 },
  { code: "as", name: "American Samoa", plate: 8 },
  { code: "at", name: "Austria", plate: 9 },
  { code: "au", name: "Australia", plate: 10 },
  { code: "aw", name: "Aruba", plate: 11 },
  { code: "az", name: "Azerbaijan", plate: 12 },
  { code: "ba", name: "Bosnia and Herzegovina", plate: 13 },
  { code: "bb", name: "Barbados", plate: 14 },
  { code: "bd", name: "Bangladesh", plate: 15 },
  { code: "be", name: "Belgium", plate: 16 },
  { code: "bf", name: "Burkina Faso", plate: 17 },
  { code: "bg", name: "Bulgaria", plate: 18 },
  { code: "bh", name: "Bahrain", plate: 19 },
  { code: "bi", name: "Burundi", plate: 20 },
  { code: "bj", name: "Benin", plate: 21 },
  { code: "bl", name: "Saint-Barthélemy", plate: 22 },
  { code: "bm", name: "Bermuda", plate: 23 },
  { code: "bn", name: "Brunei Darussalam", plate: 24 },
  { code: "bo", name: "Bolivia", plate: 25 },
  { code: "bqbo", name: "Netherlands", plate: 26 },
  { code: "bqsa", name: "Saba (Netherlands)", plate: 27 },
  { code: "bqse", name: "St. Eustatius (Netherlands)", plate: 28 },
  { code: "br", name: "Brazil", plate: 29 },
  { code: "bs", name: "Bahamas", plate: 30 },
  { code: "bt", name: "Bhutan", plate: 31 },
  { code: "bw", name: "Botswana", plate: 32 },
  { code: "by", name: "Belarus", plate: 33 },
  { code: "bz", name: "Belize", plate: 34 },
  { code: "ca", name: "Canada", plate: 35 },
  { code: "cd", name: "Democratic Republic of the Congo", plate: 36 },
  { code: "cf", name: "Central African Republic", plate: 37 },
  { code: "cg", name: "Republic of Congo", plate: 38 },
  { code: "ch", name: "Switzerland", plate: 39 },
  { code: "ci", name: "Côte d\'Ivoire", plate: 40 },
  { code: "cl", name: "Chile", plate: 41 },
  { code: "cm", name: "Cameroon", plate: 42 },
  { code: "cn", name: "China", plate: 43 },
  { code: "co", name: "Colombia", plate: 44 },
  { code: "cr", name: "Costa Rica", plate: 45 },
  { code: "cu", name: "Cuba", plate: 46 },
  { code: "cv", name: "Cape Verde", plate: 47 },
  { code: "cw", name: "Curaçao", plate: 48 },
  { code: "cy", name: "Cyprus", plate: 49 },
  { code: "cz", name: "Czech Republic", plate: 50 },
  { code: "de", name: "Germany", plate: 51 },
  { code: "dj", name: "Djibouti", plate: 52 },
  { code: "dk", name: "Denmark", plate: 53 },
  { code: "dm", name: "Dominica", plate: 54 },
  { code: "do", name: "Dominican Republic", plate: 55 },
  { code: "dz", name: "Algeria", plate: 56 },
  { code: "ec", name: "Ecuador", plate: 57 },
  { code: "ee", name: "Estonia", plate: 58 },
  { code: "eg", name: "Egypt", plate: 59 },
  { code: "eh", name: "Western Sahara", plate: 60 },
  { code: "er", name: "Eritrea", plate: 61 },
  { code: "es", name: "Spain", plate: 62 },
  { code: "et", name: "Ethiopia", plate: 63 },
  { code: "fi", name: "Finland", plate: 64 },
  { code: "fj", name: "Fiji", plate: 65 },
  { code: "fk", name: "Falkland Islands", plate: 66 },
  { code: "fm", name: "Federated States of Micronesia", plate: 67 },
  { code: "fo", name: "Faeroe Islands", plate: 68 },
  { code: "fr", name: "France", plate: 69 },
  { code: "ga", name: "Gabon", plate: 70 },
  { code: "gb", name: "United Kingdom", plate: 71 },
  { code: "gd", name: "Grenada", plate: 72 },
  { code: "ge", name: "Georgia", plate: 73 },
  { code: "gf", name: "French Guiana", plate: 74 },
  { code: "gh", name: "Ghana", plate: 75 },
  { code: "gl", name: "Greenland", plate: 76 },
  { code: "gm", name: "The Gambia", plate: 77 },
  { code: "gn", name: "Guinea", plate: 78 },
  { code: "gp", name: "Guadeloupe", plate: 79 },
  { code: "gq", name: "Equatorial Guinea", plate: 80 },
  { code: "gr", name: "Greece", plate: 81 },
  { code: "gt", name: "Guatemala", plate: 82 },
  { code: "gu", name: "Guam", plate: 83 },
  { code: "gw", name: "Guinea-Bissau", plate: 84 },
  { code: "gy", name: "Guyana", plate: 85 },
  { code: "hn", name: "Honduras", plate: 86 },
  { code: "hr", name: "Croatia", plate: 87 },
  { code: "ht", name: "Haiti", plate: 88 },
  { code: "hu", name: "Hungary", plate: 89 },
  { code: "id", name: "Indonesia", plate: 90 },
  { code: "ie", name: "Ireland", plate: 91 },
  { code: "il", name: "Israel", plate: 92 },
  { code: "in", name: "India", plate: 93 },
  { code: "iq", name: "Iraq", plate: 94 },
  { code: "ir", name: "Iran", plate: 95 },
  { code: "is", name: "Iceland", plate: 96 },
  { code: "it", name: "Italy", plate: 97 },
  { code: "jm", name: "Jamaica", plate: 98 },
  { code: "jo", name: "Jordan", plate: 99 },
  { code: "jp", name: "Japan", plate: 100 },
  { code: "ke", name: "Kenya", plate: 101 },
  { code: "kg", name: "Kyrgyzstan", plate: 102 },
  { code: "kh", name: "Cambodia", plate: 103 },
  { code: "km", name: "Comoros", plate: 104 },
  { code: "kn", name: "Saint Kitts and Nevis", plate: 105 },
  { code: "kp", name: "Dem. Rep. Korea", plate: 106 },
  { code: "kr", name: "Republic of Korea", plate: 107 },
  { code: "kw", name: "Kuwait", plate: 108 },
  { code: "ky", name: "Cayman Islands", plate: 109 },
  { code: "kz", name: "Kazakhstan", plate: 110 },
  { code: "la", name: "Lao PDR", plate: 111 },
  { code: "lb", name: "Lebanon", plate: 112 },
  { code: "lc", name: "Saint Lucia", plate: 113 },
  { code: "lk", name: "Sri Lanka", plate: 114 },
  { code: "lr", name: "Liberia", plate: 115 },
  { code: "ls", name: "Lesotho", plate: 116 },
  { code: "lt", name: "Lithuania", plate: 117 },
  { code: "lu", name: "Luxembourg", plate: 118 },
  { code: "lv", name: "Latvia", plate: 119 },
  { code: "ly", name: "Libya", plate: 120 },
  { code: "ma", name: "Morocco", plate: 121 },
  { code: "md", name: "Moldova", plate: 122 },
  { code: "me", name: "Montenegro", plate: 123 },
  { code: "mf", name: "Saint-Martin", plate: 124 },
  { code: "mg", name: "Madagascar", plate: 125 },
  { code: "mh", name: "Marshall Islands", plate: 126 },
  { code: "mk", name: "Macedonia", plate: 127 },
  { code: "ml", name: "Mali", plate: 128 },
  { code: "mm", name: "Myanmar", plate: 129 },
  { code: "mn", name: "Mongolia", plate: 130 },
  { code: "mp", name: "Northern Mariana Islands", plate: 131 },
  { code: "mq", name: "Martinique", plate: 132 },
  { code: "mr", name: "Mauritania", plate: 133 },
  { code: "ms", name: "Montserrat", plate: 134 },
  { code: "mt", name: "Malta", plate: 135 },
  { code: "mu", name: "Mauritius", plate: 136 },
  { code: "mv", name: "Maldives", plate: 137 },
  { code: "mw", name: "Malawi", plate: 138 },
  { code: "mx", name: "Mexico", plate: 139 },
  { code: "my", name: "Malaysia", plate: 140 },
  { code: "mz", name: "Mozambique", plate: 141 },
  { code: "na", name: "Namibia", plate: 142 },
  { code: "nc", name: "New Caledonia", plate: 143 },
  { code: "ne", name: "Niger", plate: 144 },
  { code: "ng", name: "Nigeria", plate: 145 },
  { code: "ni", name: "Nicaragua", plate: 146 },
  { code: "nl", name: "Netherlands", plate: 147 },
  { code: "no", name: "Norway", plate: 148 },
  { code: "np", name: "Nepal", plate: 149 },
  { code: "nr", name: "Nauru", plate: 150 },
  { code: "nz", name: "New Zealand", plate: 151 },
  { code: "om", name: "Oman", plate: 152 },
  { code: "pa", name: "Panama", plate: 153 },
  { code: "pe", name: "Peru", plate: 154 },
  { code: "pf", name: "French Polynesia", plate: 155 },
  { code: "pg", name: "Papua New Guinea", plate: 156 },
  { code: "ph", name: "Philippines", plate: 157 },
  { code: "pk", name: "Pakistan", plate: 158 },
  { code: "pl", name: "Poland", plate: 159 },
  { code: "pr", name: "Puerto Rico", plate: 160 },
  { code: "ps", name: "Palestine", plate: 161 },
  { code: "pt", name: "Portugal", plate: 162 },
  { code: "pw", name: "Palau", plate: 163 },
  { code: "py", name: "Paraguay", plate: 164 },
  { code: "qa", name: "Qatar", plate: 165 },
  { code: "re", name: "Reunion", plate: 166 },
  { code: "ro", name: "Romania", plate: 167 },
  { code: "rs", name: "Serbia", plate: 168 },
  { code: "ru", name: "Russian Federation", plate: 169 },
  { code: "rw", name: "Rwanda", plate: 170 },
  { code: "sa", name: "Saudi Arabia", plate: 171 },
  { code: "sb", name: "Solomon Islands", plate: 172 },
  { code: "sc", name: "Seychelles", plate: 173 },
  { code: "sd", name: "Sudan", plate: 174 },
  { code: "se", name: "Sweden", plate: 175 },
  { code: "si", name: "Slovenia", plate: 176 },
  { code: "sk", name: "Slovakia", plate: 177 },
  { code: "sl", name: "Sierra Leone", plate: 178 },
  { code: "sn", name: "Senegal", plate: 179 },
  { code: "so", name: "Somalia", plate: 180 },
  { code: "sr", name: "Suriname", plate: 181 },
  { code: "ss", name: "South Sudan", plate: 182 },
  { code: "st", name: "São Tomé and Principe", plate: 183 },
  { code: "sv", name: "El Salvador", plate: 184 },
  { code: "sx", name: "Sint Maarten", plate: 185 },
  { code: "sy", name: "Syria", plate: 186 },
  { code: "sz", name: "Swaziland", plate: 187 },
  { code: "tc", name: "Turks and Caicos Islands", plate: 188 },
  { code: "td", name: "Chad", plate: 189 },
  { code: "tg", name: "Togo", plate: 190 },
  { code: "th", name: "Thailand", plate: 191 },
  { code: "tj", name: "Tajikistan", plate: 192 },
  { code: "tl", name: "Timor-Leste", plate: 193 },
  { code: "tm", name: "Turkmenistan", plate: 194 },
  { code: "tn", name: "Tunisia", plate: 195 },
  { code: "to", name: "Tonga", plate: 196 },
  { code: "tr", name: "Turkey", plate: 197 },
  { code: "tt", name: "Trinidad and Tobago", plate: 198 },
  { code: "tv", name: "Tuvalu", plate: 199 },
  { code: "tw", name: "Taiwan", plate: 200 },
  { code: "tz", name: "Tanzania", plate: 201 },
  { code: "ua", name: "Ukraine", plate: 202 },
  { code: "ug", name: "Uganda", plate: 203 },
  { code: "us", name: "United States", plate: 204 },
  { code: "uy", name: "Uruguay", plate: 205 },
  { code: "uz", name: "Uzbekistan", plate: 206 },
  { code: "vc", name: "Saint Vincent and the Grenadines", plate: 207 },
  { code: "ve", name: "Venezuela", plate: 208 },
  { code: "vg", name: "British Virgin Islands", plate: 209 },
  { code: "vi", name: "United States Virgin Islands", plate: 210 },
  { code: "vn", name: "Vietnam", plate: 211 },
  { code: "vu", name: "Vanuatu", plate: 212 },
  { code: "ws", name: "Samoa", plate: 213 },
  { code: "xk", name: "Kosovo", plate: 214 },
  { code: "ye", name: "Yemen", plate: 215 },
  { code: "yt", name: "Mayotte", plate: 216 },
  { code: "za", name: "South Africa", plate: 217 },
  { code: "zm", name: "Zambia", plate: 218 },
  { code: "zw", name: "Zimbabwe", plate: 219 },
];
